### YamlMime:ManagedReference
items:
- uid: Reveal.Sdk.RVChartSettings
  commentId: T:Reveal.Sdk.RVChartSettings
  id: RVChartSettings
  parent: Reveal.Sdk
  children:
  - Reveal.Sdk.RVChartSettings.#ctor
  - Reveal.Sdk.RVChartSettings.LeftAxisMaxValue
  - Reveal.Sdk.RVChartSettings.LeftAxisMinValue
  - Reveal.Sdk.RVChartSettings.RightAxisMaxValue
  - Reveal.Sdk.RVChartSettings.RightAxisMinValue
  langs:
  - csharp
  - vb
  name: RVChartSettings
  nameWithType: RVChartSettings
  fullName: Reveal.Sdk.RVChartSettings
  type: Class
  source:
    path: Infragistics.Reveal.SDK.Server
    isExternal: true
  assemblies:
  - Infragistics.Reveal.SDK.Server
  namespace: Reveal.Sdk
  syntax:
    content: 'public class RVChartSettings : Object'
    content.vb: >-
      Public Class RVChartSettings
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Reveal.Sdk.RVChartSettings.#ctor
  commentId: M:Reveal.Sdk.RVChartSettings.#ctor
  id: '#ctor'
  parent: Reveal.Sdk.RVChartSettings
  langs:
  - csharp
  - vb
  name: RVChartSettings()
  nameWithType: RVChartSettings.RVChartSettings()
  fullName: Reveal.Sdk.RVChartSettings.RVChartSettings()
  type: Constructor
  source:
    path: Infragistics.Reveal.SDK.Server
    isExternal: true
  assemblies:
  - Infragistics.Reveal.SDK.Server
  namespace: Reveal.Sdk
  syntax:
    content: public RVChartSettings()
    content.vb: Public Sub New
  overload: Reveal.Sdk.RVChartSettings.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Reveal.Sdk.RVChartSettings.LeftAxisMinValue
  commentId: P:Reveal.Sdk.RVChartSettings.LeftAxisMinValue
  id: LeftAxisMinValue
  parent: Reveal.Sdk.RVChartSettings
  langs:
  - csharp
  - vb
  name: LeftAxisMinValue
  nameWithType: RVChartSettings.LeftAxisMinValue
  fullName: Reveal.Sdk.RVChartSettings.LeftAxisMinValue
  type: Property
  source:
    path: Infragistics.Reveal.SDK.Server
    isExternal: true
  assemblies:
  - Infragistics.Reveal.SDK.Server
  namespace: Reveal.Sdk
  syntax:
    content: public Nullable<double> LeftAxisMinValue { get; set; }
    parameters: []
    return:
      type: System.Nullable{System.Double}
    content.vb: Public Property LeftAxisMinValue As Nullable(Of Double)
  overload: Reveal.Sdk.RVChartSettings.LeftAxisMinValue*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Reveal.Sdk.RVChartSettings.LeftAxisMaxValue
  commentId: P:Reveal.Sdk.RVChartSettings.LeftAxisMaxValue
  id: LeftAxisMaxValue
  parent: Reveal.Sdk.RVChartSettings
  langs:
  - csharp
  - vb
  name: LeftAxisMaxValue
  nameWithType: RVChartSettings.LeftAxisMaxValue
  fullName: Reveal.Sdk.RVChartSettings.LeftAxisMaxValue
  type: Property
  source:
    path: Infragistics.Reveal.SDK.Server
    isExternal: true
  assemblies:
  - Infragistics.Reveal.SDK.Server
  namespace: Reveal.Sdk
  syntax:
    content: public Nullable<double> LeftAxisMaxValue { get; set; }
    parameters: []
    return:
      type: System.Nullable{System.Double}
    content.vb: Public Property LeftAxisMaxValue As Nullable(Of Double)
  overload: Reveal.Sdk.RVChartSettings.LeftAxisMaxValue*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Reveal.Sdk.RVChartSettings.RightAxisMinValue
  commentId: P:Reveal.Sdk.RVChartSettings.RightAxisMinValue
  id: RightAxisMinValue
  parent: Reveal.Sdk.RVChartSettings
  langs:
  - csharp
  - vb
  name: RightAxisMinValue
  nameWithType: RVChartSettings.RightAxisMinValue
  fullName: Reveal.Sdk.RVChartSettings.RightAxisMinValue
  type: Property
  source:
    path: Infragistics.Reveal.SDK.Server
    isExternal: true
  assemblies:
  - Infragistics.Reveal.SDK.Server
  namespace: Reveal.Sdk
  syntax:
    content: public Nullable<double> RightAxisMinValue { get; set; }
    parameters: []
    return:
      type: System.Nullable{System.Double}
    content.vb: Public Property RightAxisMinValue As Nullable(Of Double)
  overload: Reveal.Sdk.RVChartSettings.RightAxisMinValue*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Reveal.Sdk.RVChartSettings.RightAxisMaxValue
  commentId: P:Reveal.Sdk.RVChartSettings.RightAxisMaxValue
  id: RightAxisMaxValue
  parent: Reveal.Sdk.RVChartSettings
  langs:
  - csharp
  - vb
  name: RightAxisMaxValue
  nameWithType: RVChartSettings.RightAxisMaxValue
  fullName: Reveal.Sdk.RVChartSettings.RightAxisMaxValue
  type: Property
  source:
    path: Infragistics.Reveal.SDK.Server
    isExternal: true
  assemblies:
  - Infragistics.Reveal.SDK.Server
  namespace: Reveal.Sdk
  syntax:
    content: public Nullable<double> RightAxisMaxValue { get; set; }
    parameters: []
    return:
      type: System.Nullable{System.Double}
    content.vb: Public Property RightAxisMaxValue As Nullable(Of Double)
  overload: Reveal.Sdk.RVChartSettings.RightAxisMaxValue*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: Reveal.Sdk
  commentId: N:Reveal.Sdk
  isExternal: true
  name: Reveal.Sdk
  nameWithType: Reveal.Sdk
  fullName: Reveal.Sdk
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Reveal.Sdk.RVChartSettings.#ctor*
  commentId: Overload:Reveal.Sdk.RVChartSettings.#ctor
  isExternal: true
  name: RVChartSettings
  nameWithType: RVChartSettings.RVChartSettings
  fullName: Reveal.Sdk.RVChartSettings.RVChartSettings
- uid: Reveal.Sdk.RVChartSettings.LeftAxisMinValue*
  commentId: Overload:Reveal.Sdk.RVChartSettings.LeftAxisMinValue
  isExternal: true
  name: LeftAxisMinValue
  nameWithType: RVChartSettings.LeftAxisMinValue
  fullName: Reveal.Sdk.RVChartSettings.LeftAxisMinValue
- uid: System.Nullable{System.Double}
  commentId: '!:System.Nullable{System.Double}'
  definition: System.Nullable`1
  name: Nullable<Double>
  nameWithType: Nullable<Double>
  fullName: System.Nullable<System.Double>
  nameWithType.vb: Nullable(Of Double)
  fullName.vb: System.Nullable(Of System.Double)
  name.vb: Nullable(Of Double)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.Double
    name: Double
    nameWithType: Double
    fullName: System.Double
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.Double
    name: Double
    nameWithType: Double
    fullName: System.Double
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Nullable`1
  isExternal: true
  name: Nullable<>
  nameWithType: Nullable<>
  fullName: System.Nullable<>
  nameWithType.vb: Nullable(Of )
  fullName.vb: System.Nullable(Of )
  name.vb: Nullable(Of )
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: )
    nameWithType: )
    fullName: )
- uid: Reveal.Sdk.RVChartSettings.LeftAxisMaxValue*
  commentId: Overload:Reveal.Sdk.RVChartSettings.LeftAxisMaxValue
  isExternal: true
  name: LeftAxisMaxValue
  nameWithType: RVChartSettings.LeftAxisMaxValue
  fullName: Reveal.Sdk.RVChartSettings.LeftAxisMaxValue
- uid: Reveal.Sdk.RVChartSettings.RightAxisMinValue*
  commentId: Overload:Reveal.Sdk.RVChartSettings.RightAxisMinValue
  isExternal: true
  name: RightAxisMinValue
  nameWithType: RVChartSettings.RightAxisMinValue
  fullName: Reveal.Sdk.RVChartSettings.RightAxisMinValue
- uid: Reveal.Sdk.RVChartSettings.RightAxisMaxValue*
  commentId: Overload:Reveal.Sdk.RVChartSettings.RightAxisMaxValue
  isExternal: true
  name: RightAxisMaxValue
  nameWithType: RVChartSettings.RightAxisMaxValue
  fullName: Reveal.Sdk.RVChartSettings.RightAxisMaxValue
