### YamlMime:ManagedReference
items:
- uid: Reveal.Sdk.RVChartSettings
  commentId: T:Reveal.Sdk.RVChartSettings
  id: RVChartSettings
  parent: Reveal.Sdk
  children:
  - Reveal.Sdk.RVChartSettings.#ctor
  - Reveal.Sdk.RVChartSettings.LeftAxisMaxValue
  - Reveal.Sdk.RVChartSettings.LeftAxisMinValue
  - Reveal.Sdk.RVChartSettings.RightAxisMaxValue
  - Reveal.Sdk.RVChartSettings.RightAxisMinValue
  langs:
  - csharp
  - vb
  name: RVChartSettings
  nameWithType: RVChartSettings
  fullName: Reveal.Sdk.RVChartSettings
  type: Class
  source:
    path: RVUI.WPF
    isExternal: true
  assemblies:
  - RVUI.WPF
  namespace: Reveal.Sdk
  syntax:
    content: public class RVChartSettings
    content.vb: Public Class RVChartSettings
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Reveal.Sdk.RVChartSettings.#ctor
  commentId: M:Reveal.Sdk.RVChartSettings.#ctor
  id: '#ctor'
  parent: Reveal.Sdk.RVChartSettings
  langs:
  - csharp
  - vb
  name: RVChartSettings()
  nameWithType: RVChartSettings.RVChartSettings()
  fullName: Reveal.Sdk.RVChartSettings.RVChartSettings()
  type: Constructor
  source:
    path: RVUI.WPF
    isExternal: true
  assemblies:
  - RVUI.WPF
  namespace: Reveal.Sdk
  syntax:
    content: public RVChartSettings()
    content.vb: Public Sub New
  overload: Reveal.Sdk.RVChartSettings.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Reveal.Sdk.RVChartSettings.LeftAxisMinValue
  commentId: P:Reveal.Sdk.RVChartSettings.LeftAxisMinValue
  id: LeftAxisMinValue
  parent: Reveal.Sdk.RVChartSettings
  langs:
  - csharp
  - vb
  name: LeftAxisMinValue
  nameWithType: RVChartSettings.LeftAxisMinValue
  fullName: Reveal.Sdk.RVChartSettings.LeftAxisMinValue
  type: Property
  source:
    path: RVUI.WPF
    isExternal: true
  assemblies:
  - RVUI.WPF
  namespace: Reveal.Sdk
  syntax:
    content: public double? LeftAxisMinValue { get; set; }
    parameters: []
    return:
      type: System.Nullable{System.Double}
    content.vb: Public Property LeftAxisMinValue As Double?
  overload: Reveal.Sdk.RVChartSettings.LeftAxisMinValue*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Reveal.Sdk.RVChartSettings.LeftAxisMaxValue
  commentId: P:Reveal.Sdk.RVChartSettings.LeftAxisMaxValue
  id: LeftAxisMaxValue
  parent: Reveal.Sdk.RVChartSettings
  langs:
  - csharp
  - vb
  name: LeftAxisMaxValue
  nameWithType: RVChartSettings.LeftAxisMaxValue
  fullName: Reveal.Sdk.RVChartSettings.LeftAxisMaxValue
  type: Property
  source:
    path: RVUI.WPF
    isExternal: true
  assemblies:
  - RVUI.WPF
  namespace: Reveal.Sdk
  syntax:
    content: public double? LeftAxisMaxValue { get; set; }
    parameters: []
    return:
      type: System.Nullable{System.Double}
    content.vb: Public Property LeftAxisMaxValue As Double?
  overload: Reveal.Sdk.RVChartSettings.LeftAxisMaxValue*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Reveal.Sdk.RVChartSettings.RightAxisMinValue
  commentId: P:Reveal.Sdk.RVChartSettings.RightAxisMinValue
  id: RightAxisMinValue
  parent: Reveal.Sdk.RVChartSettings
  langs:
  - csharp
  - vb
  name: RightAxisMinValue
  nameWithType: RVChartSettings.RightAxisMinValue
  fullName: Reveal.Sdk.RVChartSettings.RightAxisMinValue
  type: Property
  source:
    path: RVUI.WPF
    isExternal: true
  assemblies:
  - RVUI.WPF
  namespace: Reveal.Sdk
  syntax:
    content: public double? RightAxisMinValue { get; set; }
    parameters: []
    return:
      type: System.Nullable{System.Double}
    content.vb: Public Property RightAxisMinValue As Double?
  overload: Reveal.Sdk.RVChartSettings.RightAxisMinValue*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Reveal.Sdk.RVChartSettings.RightAxisMaxValue
  commentId: P:Reveal.Sdk.RVChartSettings.RightAxisMaxValue
  id: RightAxisMaxValue
  parent: Reveal.Sdk.RVChartSettings
  langs:
  - csharp
  - vb
  name: RightAxisMaxValue
  nameWithType: RVChartSettings.RightAxisMaxValue
  fullName: Reveal.Sdk.RVChartSettings.RightAxisMaxValue
  type: Property
  source:
    path: RVUI.WPF
    isExternal: true
  assemblies:
  - RVUI.WPF
  namespace: Reveal.Sdk
  syntax:
    content: public double? RightAxisMaxValue { get; set; }
    parameters: []
    return:
      type: System.Nullable{System.Double}
    content.vb: Public Property RightAxisMaxValue As Double?
  overload: Reveal.Sdk.RVChartSettings.RightAxisMaxValue*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: Reveal.Sdk
  commentId: N:Reveal.Sdk
  isExternal: true
  name: Reveal.Sdk
  nameWithType: Reveal.Sdk
  fullName: Reveal.Sdk
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Reveal.Sdk.RVChartSettings.#ctor*
  commentId: Overload:Reveal.Sdk.RVChartSettings.#ctor
  isExternal: true
  name: RVChartSettings
  nameWithType: RVChartSettings.RVChartSettings
  fullName: Reveal.Sdk.RVChartSettings.RVChartSettings
- uid: Reveal.Sdk.RVChartSettings.LeftAxisMinValue*
  commentId: Overload:Reveal.Sdk.RVChartSettings.LeftAxisMinValue
  isExternal: true
  name: LeftAxisMinValue
  nameWithType: RVChartSettings.LeftAxisMinValue
  fullName: Reveal.Sdk.RVChartSettings.LeftAxisMinValue
- uid: System.Nullable{System.Double}
  commentId: T:System.Nullable{System.Double}
  parent: System
  definition: System.Nullable`1
  name: Nullable<Double>
  nameWithType: Nullable<Double>
  fullName: System.Nullable<System.Double>
  nameWithType.vb: Nullable(Of Double)
  fullName.vb: System.Nullable(Of System.Double)
  name.vb: Nullable(Of Double)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.Double
    name: Double
    nameWithType: Double
    fullName: System.Double
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.Double
    name: Double
    nameWithType: Double
    fullName: System.Double
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Nullable`1
  commentId: T:System.Nullable`1
  isExternal: true
  name: Nullable<T>
  nameWithType: Nullable<T>
  fullName: System.Nullable<T>
  nameWithType.vb: Nullable(Of T)
  fullName.vb: System.Nullable(Of T)
  name.vb: Nullable(Of T)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: Reveal.Sdk.RVChartSettings.LeftAxisMaxValue*
  commentId: Overload:Reveal.Sdk.RVChartSettings.LeftAxisMaxValue
  isExternal: true
  name: LeftAxisMaxValue
  nameWithType: RVChartSettings.LeftAxisMaxValue
  fullName: Reveal.Sdk.RVChartSettings.LeftAxisMaxValue
- uid: Reveal.Sdk.RVChartSettings.RightAxisMinValue*
  commentId: Overload:Reveal.Sdk.RVChartSettings.RightAxisMinValue
  isExternal: true
  name: RightAxisMinValue
  nameWithType: RVChartSettings.RightAxisMinValue
  fullName: Reveal.Sdk.RVChartSettings.RightAxisMinValue
- uid: Reveal.Sdk.RVChartSettings.RightAxisMaxValue*
  commentId: Overload:Reveal.Sdk.RVChartSettings.RightAxisMaxValue
  isExternal: true
  name: RightAxisMaxValue
  nameWithType: RVChartSettings.RightAxisMaxValue
  fullName: Reveal.Sdk.RVChartSettings.RightAxisMaxValue
