### YamlMime:ManagedReference
items:
- uid: Reveal.Sdk.MapVisualizationsConfiguration
  commentId: T:Reveal.Sdk.MapVisualizationsConfiguration
  id: MapVisualizationsConfiguration
  parent: Reveal.Sdk
  children:
  - Reveal.Sdk.MapVisualizationsConfiguration.ShapefilesCachePath
  - Reveal.Sdk.MapVisualizationsConfiguration.ShapesMetadataFileUrl
  langs:
  - csharp
  - vb
  name: MapVisualizationsConfiguration
  nameWithType: MapVisualizationsConfiguration
  fullName: Reveal.Sdk.MapVisualizationsConfiguration
  type: Class
  source:
    path: RVUI.WPF
    isExternal: true
  assemblies:
  - RVUI.WPF
  namespace: Reveal.Sdk
  syntax:
    content: public class MapVisualizationsConfiguration
    content.vb: Public Class MapVisualizationsConfiguration
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.ToString
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Reveal.Sdk.MapVisualizationsConfiguration.ShapefilesCachePath
  commentId: P:Reveal.Sdk.MapVisualizationsConfiguration.ShapefilesCachePath
  id: ShapefilesCachePath
  parent: Reveal.Sdk.MapVisualizationsConfiguration
  langs:
  - csharp
  - vb
  name: ShapefilesCachePath
  nameWithType: MapVisualizationsConfiguration.ShapefilesCachePath
  fullName: Reveal.Sdk.MapVisualizationsConfiguration.ShapefilesCachePath
  type: Property
  source:
    path: RVUI.WPF
    isExternal: true
  assemblies:
  - RVUI.WPF
  namespace: Reveal.Sdk
  summary: "\nDirectory where the shape files needed for map visualizations will be stored.\n"
  syntax:
    content: public string ShapefilesCachePath { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property ShapefilesCachePath As String
  overload: Reveal.Sdk.MapVisualizationsConfiguration.ShapefilesCachePath*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Reveal.Sdk.MapVisualizationsConfiguration.ShapesMetadataFileUrl
  commentId: P:Reveal.Sdk.MapVisualizationsConfiguration.ShapesMetadataFileUrl
  id: ShapesMetadataFileUrl
  parent: Reveal.Sdk.MapVisualizationsConfiguration
  langs:
  - csharp
  - vb
  name: ShapesMetadataFileUrl
  nameWithType: MapVisualizationsConfiguration.ShapesMetadataFileUrl
  fullName: Reveal.Sdk.MapVisualizationsConfiguration.ShapesMetadataFileUrl
  type: Property
  source:
    path: RVUI.WPF
    isExternal: true
  assemblies:
  - RVUI.WPF
  namespace: Reveal.Sdk
  summary: "\nThe url where the MapData.json could be retrieved from. ShapesMetadataFileUrl + &quot;MapData.json&quot; should be pointing to valid MapData.json.\n"
  syntax:
    content: public string ShapesMetadataFileUrl { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property ShapesMetadataFileUrl As String
  overload: Reveal.Sdk.MapVisualizationsConfiguration.ShapesMetadataFileUrl*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: Reveal.Sdk
  commentId: N:Reveal.Sdk
  isExternal: true
  name: Reveal.Sdk
  nameWithType: Reveal.Sdk
  fullName: Reveal.Sdk
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Reveal.Sdk.MapVisualizationsConfiguration.ShapefilesCachePath*
  commentId: Overload:Reveal.Sdk.MapVisualizationsConfiguration.ShapefilesCachePath
  isExternal: true
  name: ShapefilesCachePath
  nameWithType: MapVisualizationsConfiguration.ShapefilesCachePath
  fullName: Reveal.Sdk.MapVisualizationsConfiguration.ShapefilesCachePath
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Reveal.Sdk.MapVisualizationsConfiguration.ShapesMetadataFileUrl*
  commentId: Overload:Reveal.Sdk.MapVisualizationsConfiguration.ShapesMetadataFileUrl
  isExternal: true
  name: ShapesMetadataFileUrl
  nameWithType: MapVisualizationsConfiguration.ShapesMetadataFileUrl
  fullName: Reveal.Sdk.MapVisualizationsConfiguration.ShapesMetadataFileUrl
