### YamlMime:UniversalReference
items:
  - uid: rpembedded.RVChartSettings
    id: rpembedded.RVChartSettings
    name: RVChartSettings
    summary: The class representing the chart settings for a visualization.
    fullName: rpembedded.RVChartSettings
    type: Class
    children:
      - rpembedded.RVChartSettings.#ctor
    langs:
      - js
  - id: rpembedded.RVChartSettings.#ctor
    uid: rpembedded.RVChartSettings.#ctor
    parent: rpembedded.RVChartSettings
    name: RVChartSettings()
    fullName: rpembedded.RVChartSettings.RVChartSettings()
    summary: ''
    type: Constructor
    syntax:
      content: new RVChartSettings()
    langs:
      - js
